version: "3"
services:
  server:
    image: dauleduc2/clothesshopserver
    ports:
      - 3001:3001
    env_file:
      - ./.env.production
    volumes:
      - images:/uploads
  client:
    image: dauleduc2/clothesshopweb
    ports:
      - 3000:3000

  db:
    hostname: mysql
    restart: always
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: clothesshop
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
  images:
