version: "3"
services:
  server:
    build: ./backend
    image: dauleduc2/clothesshopserver
    ports:
      - 3001:3001
    env_file:
      - ./backend/src/config/.env.production
    volumes:
      - ./backend/uploads:/app/uploads
  client:
    build: "./frontend"
    image: dauleduc2/clothesshopweb
    ports:
      - 3000:3000

  db:
    hostname: mysql
    restart: always
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: clothesshop
      MYSQL_USER: "user"
      MYSQL_PASS: "123456"
    volumes:
      - clothesshop:/var/lib/mysql
volumes:
  clothesshop:
