version: "3"
services:
  server:
    image: dauleduc2/clothesshopserver
    ports:
      - 4002:4002
    env_file:
      - .env.production
    volumes:
      - images:/uploads
  client:
    image: dauleduc2/clothesshopweb
    ports:
      - 3002:3002
volumes:
  images:
