version: "3"
services:
  server:
    build: ./backend
    image: dauleduc2/clothesshopserver
    ports:
      - 3002:3002
    env_file:
      - .env.production
    volumes:
      - ./backend/uploads:/app/uploads
  client:
    build: ./frontend
    image: dauleduc2/clothesshopweb
    ports:
      - 4002:4002
  db:
    hostname: mysql
    restart: always
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "clothesshop"
      MYSQL_USER: "user"
      MYSQL_PASS: "123456"
volumes:
  clothesshop:
