import { ProductFields } from "../ProductContainer";

export const Products: Array<ProductFields> = [
    {
        productId: "1",
        imgUrl: "/images/sus1.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 1",
        price: 199000,
    },
    {
        productId: "2",
        imgUrl: "/images/sus2.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 2",
        price: 199000,
    },
    {
        productId: "3",
        imgUrl: "/images/sus3.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
    {
        productId: "4",
        imgUrl: "/images/sus4.jpg",
        describe: "Amongus bla blas bla bla bla bla bla bla bla bla bl bla 3",
        price: 199000,
    },
];
